# SPDX-FileCopyrightText: 2024 © Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: Olena Hrynenko <olena.hrynenko@idiap.ch>
#
# SPDX-License-Identifier: GPL-3.0-only

path_to_data="ADD YOUR PATH HERE" 

max_likert_distance=50
number_of_likert_variables=14

num_of_participants_generation_set=30

path_to_r_results="R_output_generation_set/"
path_to_parsed_results="Converted_R_output_generation_set/"

feature_vector_generation_set_p="feature_vector_generation_set_p_dummy.csv"
feature_vector_generation_set_p_prime="feature_vector_generation_set_p_prime_dummy.csv"

dissimilarity_matrix_generation_set="dissimilarity_matrix_generation_set.csv"
dendrogram_clusters_and_sizes_generation_set="dendrogram_clusters_and_sizes_generation_set.csv"
dendrogram_cluster_descriptors_non_normalised_generation_set="dendrogram_cluster_descriptors_non_normalised_generation_set.csv"

dendrogram_cluster_splits_generation_set="dendrogram_cluster_splits_generation_set.csv"
dendrogram_cluster_splits_and_renaming_generation_set="dendrogram_cluster_splits_and_renaming_generation_set.csv"
